### ISSUE TITLE
visible scrollbar

### ISSUE THREAD

**Issue by ackvf** [kumom/radix-converter#1]
Hi, the scrollbars are little disturbing, Chrome:
![image](https://user-images.githubusercontent.com/2313018/75229523-5fb95c80-57b2-11ea-9a6c-cfeb1f7dd339.png)

**Comment by singjyuwong** [comment]
It is indeed disturbing. What OS are you using and which version of Chrome is it?

**Comment by ackvf** [comment]
Chrome: Version 80.0.3987.122 (Official Build) (64-bit)
Windows 10
system DPI Scaling 150% (no browser zoom)

If I disable the `overflow` on the `.radix-number` it obviously disappears.

The following screenshot is from my phone, Chrome, Android. The lines appear briefly every time I type a number but then fade away.

**Comment by ackvf** [comment]
![Screenshot_20200228-224039_Chrome](https://user-images.githubusercontent.com/2313018/75589648-9e356c80-5a7b-11ea-8022-a01d66bd86e4.jpg)

**Comment by singjyuwong** [comment]
Overflow is hidden now. The new version autoresizes the number container.
