### ISSUE TITLE
press up/down to increment/decrement

### ISSUE THREAD

**Issue by ackvf** [kumom/radix-converter#2]
This is a great tool for figuring out the "magic" behind number conversions, could you implement that pressing up/down arrows increments or decrements selected input? I believe seeing the number transitions would be satisfying 😃

**Comment by singjyuwong** [comment]
Use KeyUp/KeyDown event to increment/decrement the value would be inappropriate in the latest version, because the number container would resize based on the content, meaning there can be multiple lines displayed for a number.

I added two buttons next two each number instead.

**Comment by ackvf** [comment]
I wanted to see the change live, but I get 404s and a blank page.
![image](https://user-images.githubusercontent.com/2313018/109978327-11606700-7cfe-11eb-9185-0a91626358c4.png)

**Comment by singjyuwong** [comment]
> I wanted to see the change live, but I get 404s and a blank page.
> ![image](https://user-images.githubusercontent.com/2313018/109978327-11606700-7cfe-11eb-9185-0a91626358c4.png)

I made DNS changes yesterday, so it may take 24-48 hours for the changes to fully take effect.

Alternatively, you can always clone the repo and run it locally by doing `npm install; npm run start`
